packages:
  - internal/*
  - packages/*
  - apps/*
  - docs
  - playground

catalog:
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  '@types/markdown-it': ^14.1.2
  '@vitejs/plugin-vue': ^5.0.0
  'autoprefixer': ^10.4.21
  'sass': ^1.89.2
  'typescript': ^5.0.0
  'vite': ^6.3.5
  'vite-plugin-dts': ^3.0.0
  'vue-tsc': ^3.0.1
  'turbo': ^2.5.5
  'dompurify': ^3.2.6
  'highlight.js': ^11.11.1
  'markdown-it': ^14.1.0
  'lodash-es': ^4.17.21
  '@datatraccorporation/markdown-it-mermaid': ^0.5.0
  'markdown-it-emoji': ^3.0.0
  'markdown-it-plantuml': ^1.4.1
  '@types/node': '20.14.8'
  'vite-plugin-css-injected-by-js': 3.5.2
  "@arco-design/web-vue": ^2.57.0