/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    Aside: typeof import('./src/components/Layout/Aside.vue')['default']
    Bubble: typeof import('./src/components/Bubble/Bubble.vue')['default']
    BubbleList: typeof import('./src/components/Bubble/BubbleList.vue')['default']
    BubbleLoading: typeof import('./src/components/Bubble/BubbleLoading.vue')['default']
    Button: typeof import('./src/components/Input/components/button.vue')['default']
    CodeBlock: typeof import('./src/components/MarkdownRender/components/CodeBlock.vue')['default']
    CommandTrigger: typeof import('./src/components/Input/components/CommandTrigger.vue')['default']
    Content: typeof import('./src/components/Layout/Content.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    LoadingIcon: typeof import('./src/components/Input/components/LoadingIcon.vue')['default']
    MarkdownRender: typeof import('./src/components/MarkdownRender/MarkdownRender.vue')['default']
    Mention: typeof import('./src/components/Mention/Mention.vue')['default']
    MermaidBlock: typeof import('./src/components/MarkdownRender/components/MermaidBlock.vue')['default']
    Prompt: typeof import('./src/components/Prompt/Prompt.vue')['default']
    Sender: typeof import('./src/components/Layout/Sender.vue')['default']
    SendIcon: typeof import('./src/components/Input/components/SendIcon.vue')['default']
    Textarea: typeof import('./src/components/Input/components/textarea.vue')['default']
    ThinkBlock: typeof import('./src/components/MarkdownRender/components/ThinkBlock.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/Typewriter.vue')['default']
    VoiceInput: typeof import('./src/components/Input/components/VoiceInput.vue')['default']
  }
}
